# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='address',
            field=models.CharField(default='Unknown', max_length=60),
        ),
    ]
