# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170903_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='topost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
            preserve_default=False,
        ),
    ]
