# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170903_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blogcomment',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='post',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
            preserve_default=False,
        ),
    ]
