# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170903_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='topost',
            new_name='post',
        ),
    ]
