# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170903_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='post',
            new_name='topost',
        ),
    ]
