# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170904_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='topost',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
            preserve_default=False,
        ),
    ]
