# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20170910_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ips',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=''),
        ),
    ]
