# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20170910_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ips',
        ),
    ]
